version: "3"
   
services:
  app:
    build: .
    volumes:
        - .:/GTA_marketplace
    ports:
        - "8000:8000"
    image: app:GTA_marketplace
    container_name: GTA_marketplace
    command: python3 manage.py runserver 0.0.0.0:8000
    
    